-- 26_schema_document_archive.sql
--
-- Archiv vystavených dokladů (generator-dokumentu.html) - uloží vygenerované
-- PDF do Storage a metadata do tabulky, ať je jde zpětně dohledat a stáhnout
-- (archiv.html), ne jen v okamžik vygenerování stáhnout a zapomenout.
--
-- Bucket je privátní (public = false) - přístup jen přes RLS politiky na
-- storage.objects, cesta objektu vždy začíná "<user_id>/", takže si
-- uživatelé nemůžou číst/mazat cizí soubory.

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

create policy "Users can upload own documents"
  on storage.objects for insert
  with check (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can read own documents"
  on storage.objects for select
  using (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can delete own documents"
  on storage.objects for delete
  using (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);

create table if not exists generated_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  doc_type text not null check (doc_type in ('faktura', 'storno', 'upominka', 'smlouva')),
  doc_number text,
  counterparty_name text,
  amount numeric,
  storage_path text not null,
  created_at timestamptz not null default now()
);

alter table generated_documents enable row level security;

create policy "Users can view own documents"
  on generated_documents for select
  using (auth.uid() = user_id);

create policy "Users can insert own documents"
  on generated_documents for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own documents"
  on generated_documents for delete
  using (auth.uid() = user_id);

create index if not exists generated_documents_user_id_idx on generated_documents (user_id, created_at desc);
