-- 27_schema_recurring_invoices.sql
--
-- Opakující se faktury (faktury.html) - šablona, ze které denní cron
-- (recurring-invoices-run) vytvoří záznam ve Sledování faktur a pošle
-- uživateli e-mail připomínku. VĚDOMĚ negeneruje a neodesílá PDF samo -
-- jsPDF běží na klientovi (Canvas API pro obrázky/QR kód), v Deno edge
-- funkci by to bylo nutné ověřovat zvlášť a riziko je zbytečné, když si
-- uživatel PDF stejně chce před odesláním zkontrolovat. Cron tedy jen
-- předpřipraví evidenční řádek a připomene - samotné vystavení dokladu
-- (a jeho případné odeslání e-mailem) zůstává na uživateli v Generátoru
-- dokumentů, kde se navíc rovnou uloží i do archivu (26_schema_document_archive.sql).

create table if not exists recurring_invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  counterparty_name text not null,
  counterparty_ico text,
  amount numeric not null,
  vat_amount numeric not null default 0,
  note text,
  interval_unit text not null check (interval_unit in ('monthly', 'quarterly', 'yearly')),
  due_days integer not null default 14,
  next_run_date date not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table recurring_invoices enable row level security;

create policy "Users can view own recurring invoices"
  on recurring_invoices for select
  using (auth.uid() = user_id);

create policy "Users can insert own recurring invoices"
  on recurring_invoices for insert
  with check (auth.uid() = user_id);

create policy "Users can update own recurring invoices"
  on recurring_invoices for update
  using (auth.uid() = user_id);

create policy "Users can delete own recurring invoices"
  on recurring_invoices for delete
  using (auth.uid() = user_id);

create index if not exists recurring_invoices_due_idx on recurring_invoices (next_run_date) where active = true;
